### ISSUE TITLE
Dynamic Refactor Sprint

### ISSUE THREAD

**Issue by dillydally414** [sandboxnu/edulaw#48]
**Problem:** Some of the old dynamic code is a little janky.
**Solution:** Refactor that bad boy
**Description:**
Crank as much as you can out at next Sunday's GM, then we'll do a rapid-fire PR review and merge it in to reduce the :chungus: amount of conflicts that will probably occur. Below is a draft checklist of things that we might want to consider refactoring. Note that this is not all-encompassing nor prioritized, so something on here might be lower priority than something I forgot to include.
**Incomplete checklist:**
- [x] Types
  - [x] Question type enum
  - [x] Question component similar props - MyContinue, MyInput, etc. have shared props
  - [ ] FormAnswer type
  - [x] In general, making strings strings and numbers numbers instead of having `parseInt` and `toString` everywhere
- [x] DynamicPOC/DynamicForm
  - [x] Uncoupling currentQuestion and currentAnswer as much as possible
  - [x] Making handleNext, handleBack, etc clearer to read (and abstracting out duplicated code)
  - [x] If not addressed in #45, abstracting `QuestionLayout` out of each specific question type since the layout stays consistent

**Comment by clue4** [comment]
Question component similar props - MyContinue, MyInput, etc. have shared props
-- these are relatively different enough, checking off but no changes

**Comment by clue4** [comment]
We couldn't get rid of the wrapper for FormAnswer, as this caused very confusing and so far unsolved aur naur bugs with the input question, where upon going back, it tries to populate the text field with an object rather than the previous text/actual answer

something due to field from formik, but there's very little documentation on it and it's not worth any additional dev time for such a minor change (for now.... perhaps)
